# -------------------------------------------------------------------------------------
# Author Configuration | 作者配置
# -------------------------------------------------------------------------------------

name = "uyaki"
email = "737376326@qq.com"
link = "https://uyaki.github.io"
avatar = "/images/avatar.png"